//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ploteus.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ploteus.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LearningOpportunityId1|-|FR|-|Title1|-|NonPreferredTerm1|-|MoreInfo1|-|Description1|-|http://www.google.com|-|24|-|01|-|001|-|fr|-|1|-|1|-|IP|-|fr|-|FT|-|1Y|-|DurationInformation1|-|StartDate1|-|QualificationAwarded1_1|q|OtherQualificationAwardedTerm1_1|q|http://www.google.com|q|QualificationAwardedDescription1_1|q|AwardingBody1_1|q|AwardingBodyContactInfo1_1|q|http://www.google.com|s|QualificationAwarded1_2|q|OtherQualificationAwardedTerm1_2|q|http://www.google.com|q|QualificationAwardedDescription1_2|q|Aw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lo_full_sample {
            get {
                return ResourceManager.GetString("lo_full_sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualificationId2|-|Title2|-|NonPreferredTerms2|-|Description2|-|FurtherInfo2|-|SourceOfFurtherInfo2|-|http://www.google.com|-|2|-|1|-|002|-|cs|-|AwardingBody2|-|AwardingBodyContactInfo2|-|http://www.google.com|-|SourceOfInformation2|-|cs|-|http://www.google.com|-|NationalOccupationClassification2|-|RelationshipType2|-|ExpiryDate2|-|AccessRequirements2|-|WaysToAcquire2|-|CZ
        ///QualificationId3|-|Title3|-|NonPreferredTerms3|-|Description3|-|FurtherInfo3|-|SourceOfFurtherInfo3|-|http://www.google.com|-|3|-|2|-|0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string qual_full_sample {
            get {
                return ResourceManager.GetString("qual_full_sample", resourceCulture);
            }
        }
    }
}
