//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ploteus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ploteus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///    targetNamespace=&quot;http://ec.europa.eu/delete/v0_1_1&quot;
        ///    xmlns:tns=&quot;http://ec.europa.eu/delete/v0_1_1&quot;
        ///    xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///    elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xsd:element name=&quot;Delete&quot;&gt;
        ///        &lt;xsd:complexType&gt;
        ///            &lt;xsd:sequence&gt;
        ///                &lt;xsd:element minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot; ref=&quot;tns:EntityType&quot;/&gt;
        ///				&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string delete_v0_1_1 {
            get {
                return ResourceManager.GetString("delete_v0_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:tns=&quot;http://ec.europa.eu/LearningOpportunities/v0_5_10&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://ec.europa.eu/LearningOpportunities/v0_5_10&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;element name=&quot;LearningOpportunities&quot;&gt;
        ///    &lt;complexType&gt;
        ///      &lt;sequence&gt;
        ///        &lt;element ref=&quot;tns:LearningOpportunity&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;unbounded&quot;/&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string learningOpportunities_v0_5_10 {
            get {
                return ResourceManager.GetString("learningOpportunities_v0_5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:tns=&quot;http://ec.europa.eu/Qualifications/v0_7_10&quot; targetNamespace=&quot;http://ec.europa.eu/Qualifications/v0_7_10&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///  &lt;xsd:element name=&quot;Qualifications&quot;&gt;
        ///    &lt;xsd:complexType&gt;
        ///      &lt;xsd:sequence&gt;
        ///        &lt;xsd:element ref=&quot;tns:Qualification&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;unbounded&quot;/&gt;
        ///      &lt;/xsd:sequence&gt;
        ///      &lt;xsd:attribute  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string qualifications_v0_7_10 {
            get {
                return ResourceManager.GetString("qualifications_v0_7_10", resourceCulture);
            }
        }
    }
}
